/**
 * Utilidad para manejar códigos de países e indicativos telefónicos
 */

export interface CountryCode {
  countryCode: string;
  indicativo: number;
}

export const countryCodes: CountryCode[] = [
  { countryCode: "AF", indicativo: 93 },
  { countryCode: "AL", indicativo: 355 },
  { countryCode: "DE", indicativo: 49 },
  { countryCode: "AD", indicativo: 376 },
  { countryCode: "AO", indicativo: 244 },
  { countryCode: "AI", indicativo: 1 },
  { countryCode: "AQ", indicativo: 672 },
  { countryCode: "AG", indicativo: 1 },
  { countryCode: "SA", indicativo: 966 },
  { countryCode: "DZ", indicativo: 213 },
  { countryCode: "AR", indicativo: 54 },
  { countryCode: "AM", indicativo: 374 },
  { countryCode: "AW", indicativo: 297 },
  { countryCode: "AU", indicativo: 61 },
  { countryCode: "AT", indicativo: 43 },
  { countryCode: "AZ", indicativo: 994 },
  { countryCode: "BS", indicativo: 1 },
  { countryCode: "BD", indicativo: 880 },
  { countryCode: "BB", indicativo: 1 },
  { countryCode: "BH", indicativo: 973 },
  { countryCode: "BE", indicativo: 32 },
  { countryCode: "BZ", indicativo: 501 },
  { countryCode: "BJ", indicativo: 229 },
  { countryCode: "BM", indicativo: 1 },
  { countryCode: "BY", indicativo: 375 },
  { countryCode: "BO", indicativo: 591 },
  { countryCode: "BA", indicativo: 387 },
  { countryCode: "BW", indicativo: 267 },
  { countryCode: "BR", indicativo: 55 },
  { countryCode: "BN", indicativo: 673 },
  { countryCode: "BG", indicativo: 359 },
  { countryCode: "BF", indicativo: 226 },
  { countryCode: "BI", indicativo: 257 },
  { countryCode: "BT", indicativo: 975 },
  { countryCode: "CV", indicativo: 238 },
  { countryCode: "KH", indicativo: 855 },
  { countryCode: "CM", indicativo: 237 },
  { countryCode: "CA", indicativo: 1 },
  { countryCode: "QA", indicativo: 974 },
  { countryCode: "TD", indicativo: 235 },
  { countryCode: "CL", indicativo: 56 },
  { countryCode: "CN", indicativo: 86 },
  { countryCode: "CY", indicativo: 357 },
  { countryCode: "CO", indicativo: 57 },
  { countryCode: "KM", indicativo: 269 },
  { countryCode: "CG", indicativo: 242 },
  { countryCode: "KP", indicativo: 850 },
  { countryCode: "KR", indicativo: 82 },
  { countryCode: "CI", indicativo: 225 },
  { countryCode: "CR", indicativo: 506 },
  { countryCode: "HR", indicativo: 385 },
  { countryCode: "CU", indicativo: 53 },
  { countryCode: "DK", indicativo: 45 },
  { countryCode: "DM", indicativo: 1 },
  { countryCode: "EC", indicativo: 593 },
  { countryCode: "EG", indicativo: 20 },
  { countryCode: "SV", indicativo: 503 },
  { countryCode: "AE", indicativo: 971 },
  { countryCode: "ER", indicativo: 291 },
  { countryCode: "SK", indicativo: 421 },
  { countryCode: "SI", indicativo: 386 },
  { countryCode: "ES", indicativo: 34 },
  { countryCode: "US", indicativo: 1 },
  { countryCode: "EE", indicativo: 372 },
  { countryCode: "ET", indicativo: 251 },
  { countryCode: "FJ", indicativo: 679 },
  { countryCode: "PH", indicativo: 63 },
  { countryCode: "FI", indicativo: 358 },
  { countryCode: "FR", indicativo: 33 },
  { countryCode: "GA", indicativo: 241 },
  { countryCode: "GM", indicativo: 220 },
  { countryCode: "GE", indicativo: 995 },
  { countryCode: "GH", indicativo: 233 },
  { countryCode: "GI", indicativo: 350 },
  { countryCode: "GD", indicativo: 1 },
  { countryCode: "GR", indicativo: 30 },
  { countryCode: "GL", indicativo: 299 },
  { countryCode: "GP", indicativo: 590 },
  { countryCode: "GU", indicativo: 1 },
  { countryCode: "GT", indicativo: 502 },
  { countryCode: "GF", indicativo: 594 },
  { countryCode: "GN", indicativo: 224 },
  { countryCode: "GQ", indicativo: 240 },
  { countryCode: "GW", indicativo: 245 },
  { countryCode: "GY", indicativo: 592 },
  { countryCode: "HT", indicativo: 509 },
  { countryCode: "HN", indicativo: 504 },
  { countryCode: "HK", indicativo: 852 },
  { countryCode: "HU", indicativo: 36 },
  { countryCode: "IN", indicativo: 91 },
  { countryCode: "ID", indicativo: 62 },
  { countryCode: "IQ", indicativo: 964 },
  { countryCode: "IR", indicativo: 98 },
  { countryCode: "IE", indicativo: 353 },
  { countryCode: "IS", indicativo: 354 },
  { countryCode: "KY", indicativo: 1 },
  { countryCode: "CC", indicativo: 61 },
  { countryCode: "CK", indicativo: 682 },
  { countryCode: "FO", indicativo: 298 },
  { countryCode: "GS", indicativo: 500 },
  { countryCode: "FK", indicativo: 500 },
  { countryCode: "MP", indicativo: 1 },
  { countryCode: "MH", indicativo: 692 },
  { countryCode: "PN", indicativo: 872 },
  { countryCode: "SB", indicativo: 677 },
  { countryCode: "TC", indicativo: 1 },
  { countryCode: "VG", indicativo: 1 },
  { countryCode: "VI", indicativo: 1 },
  { countryCode: "IL", indicativo: 972 },
  { countryCode: "IT", indicativo: 39 },
  { countryCode: "JM", indicativo: 1 },
  { countryCode: "JP", indicativo: 81 },
  { countryCode: "JO", indicativo: 962 },
  { countryCode: "KZ", indicativo: 7 },
  { countryCode: "KE", indicativo: 254 },
  { countryCode: "KG", indicativo: 996 },
  { countryCode: "KI", indicativo: 686 },
  { countryCode: "KW", indicativo: 965 },
  { countryCode: "LA", indicativo: 856 },
  { countryCode: "LS", indicativo: 266 },
  { countryCode: "LV", indicativo: 371 },
  { countryCode: "LB", indicativo: 961 },
  { countryCode: "LR", indicativo: 231 },
  { countryCode: "LY", indicativo: 218 },
  { countryCode: "LI", indicativo: 423 },
  { countryCode: "LT", indicativo: 370 },
  { countryCode: "LU", indicativo: 352 },
  { countryCode: "MO", indicativo: 853 },
  { countryCode: "MK", indicativo: 389 },
  { countryCode: "MG", indicativo: 261 },
  { countryCode: "MY", indicativo: 60 },
  { countryCode: "MW", indicativo: 265 },
  { countryCode: "MV", indicativo: 960 },
  { countryCode: "ML", indicativo: 223 },
  { countryCode: "MT", indicativo: 356 },
  { countryCode: "MA", indicativo: 212 },
  { countryCode: "MQ", indicativo: 596 },
  { countryCode: "MU", indicativo: 230 },
  { countryCode: "MR", indicativo: 222 },
  { countryCode: "MX", indicativo: 52 },
  { countryCode: "FM", indicativo: 691 },
  { countryCode: "MD", indicativo: 373 },
  { countryCode: "MC", indicativo: 377 },
  { countryCode: "MN", indicativo: 976 },
  { countryCode: "ME", indicativo: 382 },
  { countryCode: "MS", indicativo: 1 },
  { countryCode: "MZ", indicativo: 258 },
  { countryCode: "NA", indicativo: 264 },
  { countryCode: "NR", indicativo: 674 },
  { countryCode: "NP", indicativo: 977 },
  { countryCode: "NI", indicativo: 505 },
  { countryCode: "NE", indicativo: 227 },
  { countryCode: "NG", indicativo: 234 },
  { countryCode: "NU", indicativo: 683 },
  { countryCode: "NO", indicativo: 47 },
  { countryCode: "NC", indicativo: 687 },
  { countryCode: "NZ", indicativo: 64 },
  { countryCode: "OM", indicativo: 968 },
  { countryCode: "NL", indicativo: 31 },
  { countryCode: "PK", indicativo: 92 },
  { countryCode: "PW", indicativo: 680 },
  { countryCode: "PS", indicativo: 970 },
  { countryCode: "PA", indicativo: 507 },
  { countryCode: "PG", indicativo: 675 },
  { countryCode: "PY", indicativo: 595 },
  { countryCode: "PE", indicativo: 51 },
  { countryCode: "PL", indicativo: 48 },
  { countryCode: "PT", indicativo: 351 },
  { countryCode: "PR", indicativo: 1 },
  { countryCode: "GB", indicativo: 44 },
  { countryCode: "CF", indicativo: 236 },
  { countryCode: "CZ", indicativo: 420 },
  { countryCode: "DO", indicativo: 1 },
  { countryCode: "RW", indicativo: 250 },
  { countryCode: "RO", indicativo: 40 },
  { countryCode: "RU", indicativo: 7 },
  { countryCode: "WS", indicativo: 685 },
  { countryCode: "SM", indicativo: 378 },
  { countryCode: "VC", indicativo: 1 },
  { countryCode: "LC", indicativo: 1 },
  { countryCode: "ST", indicativo: 239 },
  { countryCode: "SN", indicativo: 221 },
  { countryCode: "RS", indicativo: 381 },
  { countryCode: "SC", indicativo: 248 },
  { countryCode: "SL", indicativo: 232 },
  { countryCode: "SG", indicativo: 65 },
  { countryCode: "SY", indicativo: 963 },
  { countryCode: "SO", indicativo: 252 },
  { countryCode: "LK", indicativo: 94 },
  { countryCode: "SZ", indicativo: 268 },
  { countryCode: "ZA", indicativo: 27 },
  { countryCode: "SD", indicativo: 249 },
  { countryCode: "SE", indicativo: 46 },
  { countryCode: "CH", indicativo: 41 },
  { countryCode: "SR", indicativo: 597 },
  { countryCode: "TH", indicativo: 66 },
  { countryCode: "TW", indicativo: 886 },
  { countryCode: "TZ", indicativo: 255 },
  { countryCode: "TJ", indicativo: 992 },
  { countryCode: "TL", indicativo: 670 },
  { countryCode: "TG", indicativo: 228 },
  { countryCode: "TO", indicativo: 676 },
  { countryCode: "TT", indicativo: 1 },
  { countryCode: "TN", indicativo: 216 },
  { countryCode: "TM", indicativo: 993 },
  { countryCode: "TR", indicativo: 90 },
  { countryCode: "TV", indicativo: 688 },
  { countryCode: "UA", indicativo: 380 },
  { countryCode: "UG", indicativo: 256 },
  { countryCode: "UY", indicativo: 598 },
  { countryCode: "UZ", indicativo: 998 },
  { countryCode: "VU", indicativo: 678 },
  { countryCode: "VE", indicativo: 58 },
  { countryCode: "VN", indicativo: 84 },
  { countryCode: "YE", indicativo: 967 },
  { countryCode: "DJ", indicativo: 253 },
  { countryCode: "ZM", indicativo: 260 },
  { countryCode: "ZW", indicativo: 263 }
];

/**
 * Obtiene el indicativo telefónico de un país por su código ISO
 * @param countryCode Código ISO del país (ej: "CO", "US", "ES")
 * @returns El indicativo telefónico o null si no se encuentra
 */
export function getCountryIndicativo(countryCode: string): number | null {
  const country = countryCodes.find(c => c.countryCode === countryCode.toUpperCase());
  return country ? country.indicativo : null;
}

/**
 * Genera el número de teléfono completo combinando el indicativo del país y el número local
 * @param countryCode Código ISO del país (ej: "CO", "US", "ES")
 * @param phone Número de teléfono local (puede ser cualquier tipo)
 * @returns El número de teléfono completo o null si no se puede generar
 */
export function generateFullPhone(countryCode: string, phone: any): string | null {
  const indicativo = getCountryIndicativo(countryCode);
  if (!indicativo || !phone) {
    return null;
  }
  
  // Convertir phone a string y limpiar
  const phoneString = String(phone).trim();
  if (!phoneString) {
    return null;
  }
  
  // Limpiar el número de teléfono de espacios y caracteres especiales
  const cleanPhone = phoneString.replace(/\D/g, '');
  
  // Verificar que el número limpio no esté vacío
  if (!cleanPhone) {
    return null;
  }
  
  // Concatenar indicativo + número
  return `${indicativo}${cleanPhone}`;
} 