name: Despliegue Automatizado gemini

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: BACKEND_SECRETS

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Definir variables en el runner
        run: |
          echo "CLIENT_NAME=${{ vars.CLIENT_NAME }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ vars.DB_NAME }}" >> $GITHUB_ENV
          echo "PORT=${{ vars.PORT }}" >> $GITHUB_ENV
          echo "SERVER_HOST=${{ vars.SERVER_HOST }}" >> $GITHUB_ENV
          echo "SERVER_USER=${{ vars.SERVER_USER }}" >> $GITHUB_ENV
          echo "DB_PASSRORD=${{ secrets.DB_PASSRORD }}" >> $GITHUB_ENV
          echo "WABA_VERIFY_TOKEN=${{ secrets.WABA_VERIFY_TOKEN }}" >> $GITHUB_ENV
          echo "URL=${{ vars.URL }}" >> $GITHUB_ENV

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "$SERVER_HOST" >> ~/.ssh/known_hosts
          
      - name: Ejecutar script de despliegue en el servidor
        run: |
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST "sudo /usr/local/bin/G360co_deploy '${{ env.CLIENT_NAME }}' '${{ env.DB_NAME }}' '${{ env.URL }}' '${{ env.PORT }}' '${{ env.DB_PASSRORD }}' '${{ env.WABA_VERIFY_TOKEN }}'"
