name: Despliegue XX

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: BACKEND_SECRETS

    env:
      CLIENT_NAME: ${{ vars.CLIENT_NAME }}
      DB_NAME: ${{ vars.DB_NAME }}
      PORT: ${{ vars.PORT }}
      SERVER_HOST: ${{ vars.SERVER_HOST }}
      SERVER_USER: ${{ vars.SERVER_USER }}

    steps:
      - name: Verificar valores cargados
        run: |
          echo "CLIENT_NAME: ${{ vars.CLIENT_NAME }}"
          echo "DB_NAME: ${{ vars.DB_NAME }}"
          echo "PORT: ${{ vars.PORT }}"
          echo "SERVER_HOST: ${{ vars.SERVER_HOST }}"
          echo "SERVER_USER: ${{ vars.SERVER_USER }}"
          echo "DB_PASSRORD: ${{ secrets.DB_PASSRORD }}"
          echo "WABA_VERIFY_TOKEN: ${{ secrets.WABA_VERIFY_TOKEN }}"

      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{ vars.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Ejecutar script de despliegue en el servidor
        run: |
          ssh -i ~/.ssh/id_rsa ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} bash -s <<EOF
            export DB_PASSRORD="${{ secrets.DB_PASSRORD }}"
            export WABA_VERIFY_TOKEN="${{ secrets.WABA_VERIFY_TOKEN }}"

            CLIENTE="${{ vars.CLIENT_NAME }}"
            DB_NAME="${{ vars.DB_NAME }}"
            PORT="${{ vars.PORT }}"
            SUBDOMINIO="${CLIENTE}.g360co.com"

            BACKEND_PATH="/var/www/${CLIENTE}/backend"
            echo "Creando carpeta en: \$BACKEND_PATH"
            sudo mkdir -p "\$BACKEND_PATH"

            sudo tee "\$BACKEND_PATH/.env" > /dev/null <<EOV
                                                          DATABASE_URL="postgresql://postgres:\${DB_PASSRORD}@localhost:5432/\${DB_NAME}?schema=public"
                                                          PORT=\${PORT}
                                                          GOOGLE_APPLICATION_CREDENTIALS=./firebase-service-account.json
                                                          WABA_VERIFY_TOKEN="\${WABA_VERIFY_TOKEN}"
                                                        EOV

            sudo /usr/local/bin/G360co_deploy "\$CLIENTE" "\$DB_NAME" "\$SUBDOMINIO" "\$PORT"
          EOF