name: Deploy App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: BACKEND_SECRETS

    env:
      CLIENT_NAME: ${{ vars.CLIENT_NAME }}
      SERVER_HOST: ${{ vars.SERVER_HOST }}
      SERVER_USER: ${{ vars.SERVER_USER }}
      BACKEND_PATH: ${{ vars.BACKEND_PATH }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Validar variables
        run: |
          echo "::group::Validación de variables"
          echo "CLIENT_NAME: $CLIENT_NAME"
          echo "SERVER_HOST: $SERVER_HOST"
          echo "::endgroup::"

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Desplegar en servidor remoto
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST bash -s << EOF
            set -e
            echo "::group::Generando archivo .env"
            cat > "$BACKEND_PATH/.env" <<EOV
CLIENT_NAME=$CLIENT_NAME
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
EOV
            echo "::endgroup::"

            echo "::group::Ejecutando script de despliegue"
            cd $BACKEND_PATH
            ./G360co_deploy
            echo "::endgroup::"
EOF