name: Despliegue ??

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: BACKEND_SECRETS

    steps:
      - name: Definir variables en el runner
        run: |
          echo "CLIENT_NAME=${{ vars.CLIENT_NAME }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ vars.DB_NAME }}" >> $GITHUB_ENV
          echo "PORT=${{ vars.PORT }}" >> $GITHUB_ENV
          echo "SERVER_HOST=${{ vars.SERVER_HOST }}" >> $GITHUB_ENV
          echo "SERVER_USER=${{ vars.SERVER_USER }}" >> $GITHUB_ENV
          echo "DB_PASSRORD=${{ secrets.DB_PASSRORD }}" >> $GITHUB_ENV
          echo "WABA_VERIFY_TOKEN=${{ secrets.WABA_VERIFY_TOKEN }}" >> $GITHUB_ENV
          echo "SUBDOMINIO=${{ vars.CLIENT_NAME }}.g360co.com" >> $GITHUB_ENV

      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "$SERVER_HOST" >> ~/.ssh/known_hosts

      - name: Ejecutar script de despliegue en el servidor
        run: |
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST bash -s <<EOF
            BACKEND_PATH="/var/www/${CLIENT_NAME}/backend"
            echo "Creando carpeta en: \$BACKEND_PATH"
            sudo mkdir -p "\$BACKEND_PATH"

            sudo tee "\$BACKEND_PATH/.env" > /dev/null <<EOV
                                                          DATABASE_URL="postgresql://postgres:${DB_PASSRORD}@localhost:5432/${DB_NAME}?schema=public"
                                                          PORT=${PORT}
                                                          GOOGLE_APPLICATION_CREDENTIALS=./firebase-service-account.json
                                                          WABA_VERIFY_TOKEN="${WABA_VERIFY_TOKEN}"
                                                        EOV

            sudo /usr/local/bin/G360co_deploy "${CLIENT_NAME}" "${DB_NAME}" "${SUBDOMINIO}" "${PORT}"
          EOF