name: vars EOF Despliegue 

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: BACKEND_SECRETS

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      WABA_VERIFY_TOKEN: ${{ secrets.WABA_VERIFY_TOKEN }}
      CLIENT_NAME: ${{ vars.CLIENT_NAME }}
      DB_NAME: ${{ vars.DB_NAME }}
      PORT: ${{ vars.PORT }}
      SERVER_HOST: ${{ vars.SERVER_HOST }}
      SERVER_USER: ${{ vars.SERVER_USER }}

    steps:
      - name: Verificar valor de SERVER_HOST
        run: |
          echo "SERVER_HOST es: ${{ vars.SERVER_HOST }} - ${{ secrets.DB_PASSWORD }} juan"

      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "$SERVER_HOST" >> ~/.ssh/known_hosts

      - name: Ejecutar script de despliegue en el servidor
        run: |
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST bash -s << EOF
            CLIENTE="${vars.CLIENT_NAME}"
            DB_NAME="${vars.DB_NAME}"
            PORT="${vars.PORT}"
            DB_PASSWORD="${secrets.DB_PASSWORD}"
            WABA_VERIFY_TOKEN="${secrets.WABA_VERIFY_TOKEN}"

            BACKEND_PATH="/var/www/${vars.CLIENT_NAME}/backend"
            mkdir -p "/var/www/${vars.CLIENT_NAME}/backend"

            cat > "$BACKEND_PATH/.env" <<EOV
                                          DATABASE_URL="postgresql://postgres:${secrets.DB_PASSWORD}@localhost:5432/${vars.DB_NAME}?schema=public"
                                          PORT=${vars.PORT}
                                          GOOGLE_APPLICATION_CREDENTIALS=./firebase-service-account.json
                                          WABA_VERIFY_TOKEN="${secrets.WABA_VERIFY_TOKEN}"
                                        EOV

            /usr/local/bin/G360co_deploy "${vars.CLIENT_NAME}" "${vars.DB_NAME}" "${vars.CLIENT_NAME}.g360co.com" "$PORT"
          EOF
